version: '3.9'
services:
  mongodb:
    image: mongo:6-jammy
    restart: always
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: passwd123
    volumes:
      - data:/data/db

volumes:
  data:
